export const CHALLENGE_TYPES = {
  OBJECT_PROOF: 'OBJECT_PROOF',
  LOCATION_PROOF: 'LOCATION_PROOF',
};

export const CHALLENGE_TIMEOUT_SECONDS = 60;

export const CHALLENGE_ATTEMPT_STATUS = {
  PENDING: 'PENDING',
  PASSED: 'PASSED',
  FAILED: 'FAILED',
  ERROR: 'ERROR',
};

export const MOCK_VERIFICATION_MODES = {
  AUTO: 'AUTO',
  ALWAYS_PASS: 'ALWAYS_PASS',
  ALWAYS_FAIL: 'ALWAYS_FAIL',
  ALWAYS_ERROR: 'ALWAYS_ERROR',
};
