export const CHALLENGE_TYPES = {
  OBJECT_PROOF: 'OBJECT_PROOF',
  LOCATION_PROOF: 'LOCATION_PROOF',
};

export const CHALLENGE_TIMEOUT_SECONDS = 60;
export const MAX_CHALLENGE_REROLLS = 2;
export const MAX_CHALLENGE_ATTEMPTS = 5;
export const MAX_NETWORK_RETRIES = 1;
export const MIN_VERIFICATION_INTERVAL_MS = 3000;
export const MAX_SAME_IMAGE_RETRIES = 1;
export const OFFLINE_HOLD_DURATION_SECONDS = 5;
export const OFFLINE_MATH_QUESTION_COUNT = 3;

export const CHALLENGE_FLOW_MODES = {
  AI: 'AI',
  OFFLINE_EMERGENCY: 'OFFLINE_EMERGENCY',
};

export const CHALLENGE_ATTEMPT_STATUS = {
  PENDING: 'PENDING',
  PASSED: 'PASSED',
  FAILED: 'FAILED',
  ERROR: 'ERROR',
};

export const MOCK_VERIFICATION_MODES = {
  AUTO: 'AUTO',
  ALWAYS_PASS: 'ALWAYS_PASS',
  ALWAYS_FAIL: 'ALWAYS_FAIL',
  ALWAYS_ERROR: 'ALWAYS_ERROR',
};
